# Translation of Odoo Server.
# This file contains the translation of the following modules:
#	* account_invoice_supplier_unique
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 8.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-04-21 13:46+0000\n"
"PO-Revision-Date: 2020-04-22 13:15+0000\n"
"Language-Team: Trey <info@trey.es>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: account_invoice_supplier_unique
#: help:purchase.config.settings,inv_ref_unique:0
msgid "Block invoice validating when reference already exists"
msgstr ""

#. module: account_invoice_supplier_unique
#: help:purchase.config.settings,inv_number_unique:0
msgid "Block invoice validating when supplier number already exists"
msgstr ""

#. module: account_invoice_supplier_unique
#: code:addons/account_invoice_supplier_unique/models/invoice.py:65
#: code:addons/account_invoice_supplier_unique/models/invoice.py:40
#, python-format
msgid "Validation error!"
msgstr ""

#. module: account_invoice_supplier_unique
#: model:ir.model,name:account_invoice_supplier_unique.model_account_invoice
msgid "Invoice"
msgstr ""

#. module: account_invoice_supplier_unique
#: code:addons/account_invoice_supplier_unique/models/invoice.py:66
#, python-format
msgid "It is not possible to validate the invoice, paiment reference duplicated."
msgstr ""

#. module: account_invoice_supplier_unique
#: code:addons/account_invoice_supplier_unique/models/invoice.py:41
#, python-format
msgid "It is not possible to validate the invoice, supplier invoice number duplicated."
msgstr ""

#. module: account_invoice_supplier_unique
#: field:purchase.config.settings,inv_ref_unique:0
msgid "Supplier invoice number unique"
msgstr ""

#. module: account_invoice_supplier_unique
#: field:purchase.config.settings,inv_number_unique:0
msgid "Payment reference unique"
msgstr ""
